#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
kg_utility_reasoning_reproduce_anchor_merged.py

Purpose:
This script unifies the reproduction pipeline for the paper.
1. Calls `kg_utility_reasoning.py` (core) to reproduce the main analytical results.
2. Calls `supplier_anchor_verify_in_one_merge.py` (anchor) to reproduce supplier anchoring results.
3. Merges all resulting CSVs into a single `Paper_All_Tables_Merged.xlsx` located in `result_kg_reproduce_merge/table_merge`.

Paper Tables Mapping (Strictly matched to paper structures and Appendix):
---------------------------------------------------------
[Main Tables]
Table 1:  Descriptive statistics (Generated by Core: Table1_price_dist.csv)
Table 2:  Baseline pricing model (Generated by Core: Table2_baseline.csv)
Table 3:  Ablation study of proxy blocks (Generated by Core: Table3_ablation.csv)
Table 4:  Block-level Shapley value and Drop-one (Generated by Core: Table4_block_shapley_drop.csv)
Table 5:  Fixed Effects ablation analysis (Generated by Core: Table5_FE_ablation.csv)
Table 6:  Shapley value for Specific Fixed Effects (Generated by Core: Table6_FE_shapley.csv)
Table 7:  Mechanism proxy evaluation (Generated by Core: Table9_KG_mechanism_cv.csv -> Maps to Paper Table 7)
Table 8:  Drop-one analysis for Fixed Effects (Generated by Core: Table8_FE_dropone.csv)
Table 9:  Quantitative evidence for supplier anchoring (Generated by Anchor script: table9_supplier_anchoring_summary.csv)
Table 10: Structural vs. teleport-only heat mechanisms (Generated by Core: Table10_heat_ablation.csv)

[Appendix Tables]
Appendix G1: Mechanism-chain analysis (Generated by Core: Table11_keyfactor.csv -> Maps to Appendix Table G1)
Appendix A1: Anchor decomposition stats (Generated by Anchor script: paper_appendix_table_a1.csv)
Appendix Core 1-6: Other supplementary tables (Generated by Core: AppendixTable1.csv - AppendixTable6.csv)

Usage:
  python kg_utility_reasoning_reproduce_anchor_merged.py \
    --input ./anymous \
    --core kg_utility_reasoning.py \
    --anchor_script supplier_anchor_verify_in_one_merge.py \
    --out_dir result_kg_reproduce_merge
"""

from __future__ import annotations

import argparse
import importlib.util
import inspect
import json
import os
import sys
import types
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import re


# -----------------------------
# General Helpers
# -----------------------------
def ensure_dir(p: str) -> None:
    os.makedirs(p, exist_ok=True)


def read_json(p: str) -> Any:
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def _exists_any(root: str, names: List[str]) -> bool:
    return any(os.path.exists(os.path.join(root, n)) for n in names)


def _find_first_recursive(root: str, target_names: List[str]) -> Optional[str]:
    for cur, dirs, files in os.walk(root):
        dirs.sort()
        files_sorted = sorted(files)
        for tn in target_names:
            if tn in files_sorted:
                return os.path.join(cur, tn)
    return None


def find_anymous_root(d: str) -> str:
    d = os.path.abspath(d)

    def ok(root: str) -> bool:
        if not (os.path.exists(os.path.join(root, "name_price_anonymized.xlsx"))
                and os.path.exists(os.path.join(root, "media_result.xlsx"))
                and os.path.isdir(os.path.join(root, "neo4j_export"))):
            return False
        if not os.path.exists(os.path.join(root, "STEP0_fold_textemb_cache.npz")):
            return False
        if not _exists_any(root, ["STEP0_product_textemb.csv", "STEP0_product_textemb.npz"]):
            return False
        return True

    if ok(d): return d
    cand = os.path.join(d, "anymous")
    if ok(cand): return cand

    best = None
    for cur, dirs, files in os.walk(d):
        dirs.sort()
        if ok(cur):
            if best is None or len(cur) > len(best):
                best = cur
    if best is not None:
        return best

    raise FileNotFoundError(
        f"Cannot locate valid data root under: {d}.\n"
        "Expected to find: name_price_anonymized.xlsx, media_result.xlsx, neo4j_export/, "
        "STEP0_fold_textemb_cache.npz, STEP0_product_textemb.(csv|npz)"
    )


def load_module(name: str, path: str):
    spec = importlib.util.spec_from_file_location(name, os.path.abspath(path))
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load script: {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def load_product_embedding_table(any_root: str) -> Tuple[pd.DataFrame, List[str]]:
    csv_path = os.path.join(any_root, "STEP0_product_textemb.csv")
    npz_path = os.path.join(any_root, "STEP0_product_textemb.npz")

    if (not os.path.exists(csv_path)) and (not os.path.exists(npz_path)):
        csv_hit = _find_first_recursive(any_root, ["STEP0_product_textemb.csv"])
        npz_hit = _find_first_recursive(any_root, ["STEP0_product_textemb.npz"])
        if csv_hit: csv_path = csv_hit
        if npz_hit: npz_path = npz_hit

    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        emb_cols = [c for c in df.columns if c.startswith("textemb_")]
        df = df[["name", "supplier"] + emb_cols].copy()
        df["name"] = df["name"].astype(str)
        df["supplier"] = df["supplier"].astype(str)
        df = df.drop_duplicates(["name", "supplier"]).reset_index(drop=True)
        return df, emb_cols

    if os.path.exists(npz_path):
        npz = np.load(npz_path, allow_pickle=True)
        keys = npz["keys"]
        emb_cols = [str(x) for x in npz["emb_cols"].tolist()]
        mat = npz["mat"].astype(float)
        df = pd.DataFrame(keys, columns=["name", "supplier"])
        for j, c in enumerate(emb_cols):
            df[c] = mat[:, j]
        df["name"] = df["name"].astype(str)
        df["supplier"] = df["supplier"].astype(str)
        df = df.drop_duplicates(["name", "supplier"]).reset_index(drop=True)
        return df, emb_cols

    raise FileNotFoundError(f"Missing STEP0_product_textemb.csv/.npz under {any_root}")


def load_fold_textemb_cache(any_root: str) -> Tuple[Dict[int, np.ndarray], int, int]:
    npz_path = os.path.join(any_root, "STEP0_fold_textemb_cache.npz")
    if not os.path.exists(npz_path):
        hit = _find_first_recursive(any_root, ["STEP0_fold_textemb_cache.npz"])
        if hit: npz_path = hit
    if not os.path.exists(npz_path):
        raise FileNotFoundError(f"Missing fold text embedding cache: {npz_path}")

    npz = np.load(npz_path, allow_pickle=True)
    fold2emb: Dict[int, np.ndarray] = {}
    for k in npz.files:
        m = re.match(r"^fold(\d+)(?:_emb)?$", str(k))
        if not m: continue
        fid = int(m.group(1))
        arr = np.asarray(npz[k], dtype=float)
        fold2emb[fid] = arr

    if "n_rows" in npz.files:
        n_rows = int(np.asarray(npz["n_rows"]).reshape(-1)[0])
    else:
        n_rows = int(next(iter(fold2emb.values())).shape[0])

    if "dim_default" in npz.files:
        dim = int(np.asarray(npz["dim_default"]).reshape(-1)[0])
    else:
        dim = int(next(iter(fold2emb.values())).shape[1])

    return fold2emb, n_rows, dim


# -----------------------------
# CSV-backed DB Mock for Neo4j
# -----------------------------
class CSVNeo4jDB:
    def __init__(self, uri: str, user: str, password: str, neo_dir: str):
        self.neo_dir = os.path.abspath(str(neo_dir))
        self.nodes_dp = pd.read_csv(os.path.join(self.neo_dir, "nodes_dataproduct.csv"))
        self.nodes_supplier = pd.read_csv(os.path.join(self.neo_dir, "nodes_supplier.csv"))
        self.rel_provide = pd.read_csv(os.path.join(self.neo_dir, "rel_provides_data.csv"))
        self.rel_app = pd.read_csv(os.path.join(self.neo_dir, "rel_applied_to.csv"))
        self.rel_src = pd.read_csv(os.path.join(self.neo_dir, "rel_source_industry.csv"))

        if "src" not in self.rel_src.columns and "src_name" in self.rel_src.columns:
            self.rel_src = self.rel_src.rename(columns={"src_name": "src"})
        if "app" not in self.rel_app.columns and "app_name" in self.rel_app.columns:
            self.rel_app = self.rel_app.rename(columns={"app_name": "app"})

        ren = {}
        if "name_anon" in self.nodes_dp.columns and "name" not in self.nodes_dp.columns: ren["name_anon"] = "name"
        if "supplier_anon" in self.nodes_dp.columns and "supplier" not in self.nodes_dp.columns: ren[
            "supplier_anon"] = "supplier"
        if "desc_anon" in self.nodes_dp.columns and "desc" not in self.nodes_dp.columns: ren["desc_anon"] = "desc"
        self.nodes_dp = self.nodes_dp.rename(columns=ren)

        if "desc" not in self.nodes_dp.columns:
            self.nodes_dp["desc"] = ""

        for c in ["dp_id", "name", "supplier", "desc"]:
            self.nodes_dp[c] = self.nodes_dp[c].astype(str)

        if "src" not in self.rel_src.columns: self.rel_src["src"] = ""
        if "app" not in self.rel_app.columns: self.rel_app["app"] = ""
        self.rel_src["dp_id"] = self.rel_src["dp_id"].astype(str)
        self.rel_app["dp_id"] = self.rel_app["dp_id"].astype(str)
        self.rel_src["src"] = self.rel_src["src"].astype(str)
        self.rel_app["app"] = self.rel_app["app"].astype(str)

        self._src_map = self.rel_src.dropna(subset=["dp_id"]).groupby("dp_id")["src"].apply(self._uniq_sorted).to_dict()
        self._app_map = self.rel_app.dropna(subset=["dp_id"]).groupby("dp_id")["app"].apply(self._uniq_sorted).to_dict()

        dp_sup = self.nodes_dp[["dp_id", "supplier"]].copy()
        dp_sup["dp_id"] = dp_sup["dp_id"].astype(str)
        dp_sup["supplier"] = dp_sup["supplier"].astype(str)

        app_edges = self.rel_app[["dp_id", "app"]].copy()
        src_edges = self.rel_src[["dp_id", "src"]].copy()

        tmp = app_edges.merge(dp_sup, on="dp_id", how="left").dropna(subset=["supplier", "app"])
        self.counts_sup_app = tmp.groupby(["app", "supplier"], as_index=False)["dp_id"].nunique().rename(
            columns={"dp_id": "prod_cnt"})

        tmp2 = src_edges.merge(dp_sup, on="dp_id", how="left").dropna(subset=["supplier", "src"])
        self.counts_sup_src = tmp2.groupby(["src", "supplier"], as_index=False)["dp_id"].nunique().rename(
            columns={"dp_id": "prod_cnt"})

        tmp3 = src_edges.merge(app_edges, on="dp_id", how="inner").dropna(subset=["src", "app"])
        self.counts_src_app = tmp3.groupby(["src", "app"], as_index=False)["dp_id"].nunique().rename(
            columns={"dp_id": "prod_cnt"})

    @staticmethod
    def _uniq_sorted(x: pd.Series) -> List[str]:
        return sorted({str(v).strip() for v in x.dropna().tolist() if str(v).strip()})

    @staticmethod
    def _union_lists(series: pd.Series) -> List[str]:
        s = set()
        for lst in series.tolist():
            if isinstance(lst, list):
                for v in lst:
                    if str(v).strip(): s.add(str(v).strip())
        return sorted(s)

    def fetch_matched_multilabel(self, df_price: pd.DataFrame) -> pd.DataFrame:
        dp = self.nodes_dp[["dp_id", "name", "supplier", "desc"]].copy()
        dp["src_list"] = dp["dp_id"].map(lambda i: self._src_map.get(str(i), []))
        dp["app_list"] = dp["dp_id"].map(lambda i: self._app_map.get(str(i), []))
        kg = dp.groupby(["name", "supplier"], as_index=False).agg(
            desc=("desc", "first"),
            src_list=("src_list", self._union_lists),
            app_list=("app_list", self._union_lists),
        )
        keys = df_price[["name", "supplier"]].astype(str).drop_duplicates()
        kg = kg.merge(keys, on=["name", "supplier"], how="inner")
        return kg[["name", "supplier", "desc", "src_list", "app_list"]]

    def fetch_supplier_product_app_src_edges(self, suppliers: Optional[List[str]] = None) -> pd.DataFrame:
        dp = self.nodes_dp[["dp_id", "name", "supplier"]].copy()
        if suppliers is not None:
            sup_set = set([str(s) for s in suppliers])
            dp = dp[dp["supplier"].astype(str).isin(sup_set)].copy()
        dp["src_list"] = dp["dp_id"].map(lambda i: self._src_map.get(str(i), []))
        dp["app_list"] = dp["dp_id"].map(lambda i: self._app_map.get(str(i), []))
        edges = dp.groupby(["supplier", "name"], as_index=False).agg(
            app_list=("app_list", self._union_lists),
            src_list=("src_list", self._union_lists),
        ).rename(columns={"name": "product"})
        return edges[["supplier", "product", "app_list", "src_list"]]

    def fetch_supplier_app_counts(self) -> pd.DataFrame:
        return self.counts_sup_app[["app", "supplier", "prod_cnt"]].copy()

    def fetch_supplier_src_counts(self) -> pd.DataFrame:
        return self.counts_sup_src[["src", "supplier", "prod_cnt"]].copy()

    def fetch_src_app_counts(self) -> pd.DataFrame:
        return self.counts_src_app[["src", "app", "prod_cnt"]].copy()


# -----------------------------
# Monkeypatches for Core Script
# -----------------------------
def patch_build_X_with_product_textemb(core, df_emb_map: pd.DataFrame, emb_cols: List[str]):
    dfm = df_emb_map.copy()
    dfm["name"] = dfm["name"].astype(str)
    dfm["supplier"] = dfm["supplier"].astype(str)
    use_cols = sorted([c for c in emb_cols if c.startswith("textemb_")],
                      key=lambda c: int(re.match(r"^textemb_(\d+)$", str(c)).group(1)) if re.match(r"^textemb_(\d+)$",
                                                                                                   str(c)) else 10 ** 9)
    key2vec = {}
    for _, r in dfm[["name", "supplier"] + use_cols].dropna(subset=["name", "supplier"]).iterrows():
        key2vec[(r["name"], r["supplier"])] = r[use_cols].to_numpy(dtype=float)

    knn = core.knn
    parse_labels = core.parse_labels
    neighbor_entropy = core.neighbor_entropy
    OneHotEncoder = core.OneHotEncoder

    def build_X_cached(train_df, test_df, dim=16, knn_k=5, alpha=1.0, random_state=42):
        def mat_from_df(d: pd.DataFrame) -> np.ndarray:
            rows = []
            for n, s in zip(d["name"].astype(str).values, d["supplier"].astype(str).values):
                v = key2vec.get((n, s))
                rows.append(np.zeros((len(use_cols),), dtype=float) if v is None else v)
            M = np.vstack(rows) if rows else np.zeros((0, len(use_cols)), dtype=float)
            k = min(int(dim), M.shape[1]) if M.ndim == 2 else int(dim)
            if M.shape[1] < k:
                pad = np.zeros((M.shape[0], k - M.shape[1]), dtype=float)
                M = np.hstack([M, pad])
            return M[:, :k]

        emb_tr, emb_te = mat_from_df(train_df), mat_from_df(test_df)
        nbr_tr_idx, nbr_tr_sim = knn(emb_tr, emb_tr, k=knn_k, exclude_self=True)
        nbr_te_idx, nbr_te_sim = knn(emb_tr, emb_te, k=knn_k, exclude_self=False)

        def sim_stats(s):
            return np.vstack([s.mean(1), s.max(1), s.std(1), s.sum(1)]).T

        sim_tr, sim_te = sim_stats(nbr_tr_sim), sim_stats(nbr_te_sim)

        tr_app = [parse_labels(x) for x in train_df["app_list"].values]
        tr_src = [parse_labels(x) for x in train_df["src_list"].values]

        app_ent_tr, app_top1_tr, app_sup_tr = neighbor_entropy(tr_app, nbr_tr_idx, nbr_tr_sim)
        app_ent_te, app_top1_te, app_sup_te = neighbor_entropy(tr_app, nbr_te_idx, nbr_te_sim)
        src_ent_tr, src_top1_tr, src_sup_tr = neighbor_entropy(tr_src, nbr_tr_idx, nbr_tr_sim)
        src_ent_te, src_top1_te, src_sup_te = neighbor_entropy(tr_src, nbr_te_idx, nbr_te_sim)

        X_num_tr = np.hstack(
            [emb_tr, sim_tr, app_ent_tr[:, None], app_top1_tr[:, None], app_sup_tr[:, None], src_ent_tr[:, None],
             src_top1_tr[:, None], src_sup_tr[:, None]])
        X_num_te = np.hstack(
            [emb_te, sim_te, app_ent_te[:, None], app_top1_te[:, None], app_sup_te[:, None], src_ent_te[:, None],
             src_top1_te[:, None], src_sup_te[:, None]])

        col_means = np.nanmean(X_num_tr, axis=0)
        col_means[~np.isfinite(col_means)] = 0.0

        def impute(X):
            X2 = X.copy()
            m = ~np.isfinite(X2)
            if m.any(): X2[m] = np.take(col_means, np.where(m)[1])
            return X2

        X_num_tr, X_num_te = impute(X_num_tr), impute(X_num_te)
        ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
        X_sup_tr = ohe.fit_transform(train_df[["supplier"]].astype(str))
        X_sup_te = ohe.transform(test_df[["supplier"]].astype(str))

        return np.hstack([X_num_tr, X_sup_tr]), np.hstack([X_num_te, X_sup_te])

    core.build_X = build_X_cached


def patch_onehotencoder_compat(core):
    try:
        import sklearn.preprocessing as skp
        def OneHotEncoder_compat(*args, **kwargs):
            if "sparse" in kwargs:
                try:
                    return skp.OneHotEncoder(*args, **kwargs)
                except TypeError:
                    kwargs["sparse_output"] = kwargs.pop("sparse")
                    return skp.OneHotEncoder(*args, **kwargs)
            return skp.OneHotEncoder(*args, **kwargs)

        core.OneHotEncoder = OneHotEncoder_compat
    except Exception:
        pass


def patch_fixed_splits(core, folds_k, folds_g):
    def build_fixed_splits_patched(df, n_splits, random_state): return folds_k, folds_g

    core.build_fixed_splits = build_fixed_splits_patched


def patch_product_text_embedding(core, df_emb_map: pd.DataFrame, emb_cols: List[str]):
    def build_product_text_embedding_patched(df_rows, text_col="desc", dim=50, min_df=2, **kwargs):
        d = df_rows.copy()
        keys = d[["name", "supplier"]].astype(str).reset_index(drop=True)
        want = [f"textemb_{i}" for i in range(int(dim))]
        src_cols = [c for c in want if c in emb_cols]
        out = keys.merge(df_emb_map[["name", "supplier"] + src_cols].drop_duplicates(["name", "supplier"]),
                         on=["name", "supplier"], how="left")
        for c in want:
            if c not in out.columns: out[c] = 0.0
        out[want] = out[want].fillna(0.0).astype(float)
        return out[["name", "supplier"] + want], None

    core.build_product_text_embedding = build_product_text_embedding_patched


def patch_step0_fold_text_embedding(core, folds_k, fold2emb: Dict[int, np.ndarray]):
    orig_fit, orig_transform = getattr(core, "fit_text_embedder", None), getattr(core, "transform_text_embedder", None)
    K = len(folds_k)
    state = {"call_count": 0, "fid": 0, "train_len": None, "test_len": None, "emb_tr": None, "emb_te": None}

    def fit_text_embedder_patched(train_text, dim=50, min_df=2, **kwargs):
        state["call_count"] += 1
        fid = ((state["call_count"] - 1) % K) + 1
        state["fid"] = fid
        if fid in fold2emb:
            tr, te = np.array(folds_k[fid - 1]["train_idx"], dtype=int), np.array(folds_k[fid - 1]["test_idx"],
                                                                                  dtype=int)
            emb_all = np.asarray(fold2emb[fid], dtype=float)
            state["train_len"], state["test_len"] = int(len(tr)), int(len(te))
            state["emb_tr"], state["emb_te"] = emb_all[tr, :int(dim)], emb_all[te, :int(dim)]
            return "__CACHED__", "__CACHED__"
        return orig_fit(train_text, dim=dim, min_df=min_df)

    def transform_text_embedder_patched(tfidf, svd, texts, **kwargs):
        if tfidf == "__CACHED__" and svd == "__CACHED__":
            if state.get("train_len") is not None and len(texts) == state["train_len"]: return np.asarray(
                state["emb_tr"], dtype=float)
            return np.asarray(state["emb_te"], dtype=float)
        return orig_transform(tfidf, svd, texts)

    core.fit_text_embedder = fit_text_embedder_patched
    core.transform_text_embedder = transform_text_embedder_patched


def call_run_all_steps_compat(core, **kwargs):
    sig = inspect.signature(core.run_all_steps)
    accepted = set(sig.parameters.keys())
    filtered = {k: v for k, v in kwargs.items() if k in accepted}
    return core.run_all_steps(**filtered)


def _load_df0_for_step0(any_root: str, out_dir: str) -> pd.DataFrame:
    cand1, cand2 = os.path.join(out_dir, "STEP0_matched_dataset.csv"), os.path.join(any_root,
                                                                                    "STEP0_matched_dataset_anonymized.csv")
    return pd.read_csv(cand1 if os.path.exists(cand1) else cand2)


def _ensure_prod_key(df: pd.DataFrame) -> pd.DataFrame:
    d = df.copy()
    if "prod_key" not in d.columns and ("name" in d.columns) and ("supplier" in d.columns):
        d["prod_key"] = d.apply(lambda r: f"PROD::{str(r['name']).strip()}||SUP::{str(r['supplier']).strip()}", axis=1)
    return d


# -----------------------------
# Formatting Helpers for Excel Output
# -----------------------------
def format_table_1(df: pd.DataFrame) -> pd.DataFrame:
    if 'Unnamed: 0' in df.columns:
        df = df.drop(columns=['Unnamed: 0'])
    return df.rename(columns={
        'variable': 'Var', 'count': 'Obs', 'mean': 'Mean',
        'std': 'SD', 'min': 'Min', 'max': 'Max'
    })


def format_table_2(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename(columns={'metric': 'Metric', 'mean': 'Mean', 'std': 'SD'})


def format_table_3(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename(columns={
        'model': 'Model', 'metric': 'Metric', 'mean': 'Mean', 'std': 'SD',
        'baseline_mean': 'Baseline Mean', 'delta_vs_baseline': 'Delta vs Baseline'
    })


def format_table_5(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename(columns={
        'scenario': 'Scenario', 'metric': 'Metric', 'mean': 'Mean', 'std': 'SD',
        'baseline_mean': 'Baseline Mean', 'delta_vs_baseline': 'Delta vs Baseline'
    })


def format_table_7(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename(columns={'metric': 'Metric', 'cv R2': 'cv R2', 'MAE': 'MAE', 'RMSE': 'RMSE'})


def format_app_d1(df: pd.DataFrame) -> pd.DataFrame:
    if 'Unnamed: 0' in df.columns:
        df = df.drop(columns=['Unnamed: 0'])
    return df.rename(columns={
        'variable': 'Var', 'count': 'Obs', 'mean': 'Mean', 'std': 'SD',
        'min': 'Min', 'P25': 'P25', 'P50': 'P50', 'P75': 'P75', 'max': 'Max'
    })


def format_app_g1(df: pd.DataFrame) -> pd.DataFrame:
    return df.rename(columns={
        'dimension': 'Dimension',
        'method': 'Method',
        'term': 'Term',
        'estimate': 'Estimate',
        'ci95_low': '95% CI Lower',
        'ci95_high': '95% CI Upper',
        'ci_excludes_0': 'Excludes 0',
        'notes': 'Notes'
    })


# -----------------------------
# Strict Paper-Content Excel Merging Logic
# -----------------------------
def merge_excel(out_dir: str):
    """
    Merges strictly defined CSV files into a unified Excel workbook.
    - Accurately aligns Column Headers with Word manuscript conventions.
    - Merges split results for Table 4, 6, and 10 logically into single tables.
    - Excludes any intermediate tables (like "Anchor_*.csv") completely.
    """
    table_merge_dir = os.path.join(out_dir, "table_merge")
    ensure_dir(table_merge_dir)
    merged_path = os.path.join(table_merge_dir, "Paper_All_Tables_Merged.xlsx")

    core_csv_dir = os.path.join(out_dir, "table_out", "paper_tables_csv")
    anchor_out_dir = os.path.join(out_dir, "anchor_merge_outputs")

    with pd.ExcelWriter(merged_path, engine="openpyxl") as writer:

        def read_robust(path: str) -> Optional[pd.DataFrame]:
            if not path or not os.path.exists(path):
                return None
            if path.lower().endswith(".xlsx"):
                try:
                    return pd.read_excel(path)
                except:
                    return None
            for enc in ['utf-8', 'gbk', 'gb18030', 'utf-8-sig', 'latin1']:
                try:
                    return pd.read_csv(path, encoding=enc)
                except:
                    continue
            return None

        def add_sheet(path: str, sheet_name: str, formatter=None) -> bool:
            df = read_robust(path)
            if df is not None:
                if formatter:
                    df = formatter(df)
                df.to_excel(writer, sheet_name=sheet_name[:31], index=False)
                return True
            return False

        def find_file(directory: str, prefix: str, preferred_ext: str = ".csv") -> Optional[str]:
            if not os.path.exists(directory): return None
            matches = []
            for f in os.listdir(directory):
                if f.lower().startswith(prefix.lower()):
                    rest = f[len(prefix):]
                    if rest == "" or rest.startswith(".") or rest.startswith("_"):
                        matches.append(f)
            if not matches: return None
            for f in matches:
                if f.lower().endswith(preferred_ext): return os.path.join(directory, f)
            return os.path.join(directory, matches[0])

        # ---------------------------------------------------------
        # Main Tables 1 to 3
        # ---------------------------------------------------------
        add_sheet(find_file(core_csv_dir, "Table1"), "Table_1", format_table_1)
        add_sheet(find_file(core_csv_dir, "Table2"), "Table_2", format_table_2)
        add_sheet(find_file(core_csv_dir, "Table3"), "Table_3", format_table_3)

        # ---------------------------------------------------------
        # Table 4: Merge Shapley (Table4) + Drop-One (Table5)
        # ---------------------------------------------------------
        df_t4_s = read_robust(find_file(core_csv_dir, "Table4"))
        df_t4_d = read_robust(find_file(core_csv_dir, "Table5"))
        if df_t4_s is not None and df_t4_d is not None:
            if 'drop' in df_t4_d.columns:
                df_t4_d = df_t4_d.rename(columns={'drop': 'metric'})

            df_t4 = pd.merge(df_t4_s, df_t4_d, on='metric', how='outer')
            df_t4 = df_t4.rename(columns={
                'metric': 'Block',
                'result': 'Shapley Value',
                'R2_full': 'R2 Full',
                'R2_dropped': 'R2 Dropped',
                'delta_R2': 'Delta R2'
            })
            df_t4.to_excel(writer, sheet_name="Table_4", index=False)

        # ---------------------------------------------------------
        # Table 5: FE Ablation Tests (Core Table 6)
        # ---------------------------------------------------------
        add_sheet(find_file(core_csv_dir, "Table6"), "Table_5", format_table_5)

        # ---------------------------------------------------------
        # Table 6: Merge FE Shapley (Table7) + Drop-One (Table8)
        # ---------------------------------------------------------
        df_t6_s = read_robust(find_file(core_csv_dir, "Table7"))
        df_t6_d = read_robust(find_file(core_csv_dir, "Table8"))
        if df_t6_s is not None and df_t6_d is not None:
            if 'drop' in df_t6_d.columns:
                df_t6_d = df_t6_d.rename(columns={'drop': 'metric'})

            df_t6 = pd.merge(df_t6_s, df_t6_d, on='metric', how='outer')
            if 'cv_tag' in df_t6.columns: df_t6 = df_t6.drop(columns=['cv_tag'])
            df_t6 = df_t6.rename(columns={
                'metric': 'Fixed Effect',
                'result': 'Shapley Value',
                'R2_full': 'R2 Full',
                'R2_dropped': 'R2 Dropped',
                'delta_R2': 'Delta R2'
            })
            df_t6.to_excel(writer, sheet_name="Table_6", index=False)

        # ---------------------------------------------------------
        # Table 7: Mechanism proxy CV (Core Table 9)
        # ---------------------------------------------------------
        add_sheet(find_file(core_csv_dir, "Table9"), "Table_7", format_table_7)

        # ---------------------------------------------------------
        # Table 8: Heat Robustness (Core Table 10)
        # ---------------------------------------------------------
        add_sheet(find_file(core_csv_dir, "Table10"), "Table_8")

        # ---------------------------------------------------------
        # Table 9: Supplier Anchor
        # ---------------------------------------------------------
        fpath_t9 = find_file(anchor_out_dir, "table9_supplier_anchoring", preferred_ext=".csv")
        if not fpath_t9:
            alt_path = os.path.join(anchor_out_dir, "table9_supplier_anchoring_summary.csv")
            if os.path.exists(alt_path): fpath_t9 = alt_path
        add_sheet(fpath_t9, "Table_9")

        # ---------------------------------------------------------
        # Table 10: Validation Schemes (Core Table11 & AppendixTable5)
        # ---------------------------------------------------------
        df_t10_r = read_robust(find_file(core_csv_dir, "Table11"))
        df_t10_g = read_robust(find_file(core_csv_dir, "AppendixTable5"))
        if df_t10_r is not None and df_t10_g is not None:
            cols_to_keep = ['metric', 'mean', 'std']
            df1 = df_t10_r[cols_to_keep] if set(cols_to_keep).issubset(df_t10_r.columns) else df_t10_r
            df2 = df_t10_g[cols_to_keep] if set(cols_to_keep).issubset(df_t10_g.columns) else df_t10_g

            df_t10 = pd.merge(df1, df2, on='metric', suffixes=('_Random', '_Group'), how='outer')
            df_t10 = df_t10.rename(columns={
                'metric': 'Metric',
                'mean_Random': 'Random K-fold Mean',
                'std_Random': 'Random K-fold SD',
                'mean_Group': 'Group K-fold Mean',
                'std_Group': 'Group K-fold SD'
            })
            df_t10.to_excel(writer, sheet_name="Table_10", index=False)

        # ---------------------------------------------------------
        # Appendices Mapping (Strictly paper items)
        # ---------------------------------------------------------
        add_sheet(find_file(core_csv_dir, "AppendixTable1"), "App_Table_C1")
        add_sheet(find_file(core_csv_dir, "AppendixTable2"), "App_Table_C2")
        add_sheet(find_file(core_csv_dir, "AppendixTable3"), "App_Table_D1", format_app_d1)
        add_sheet(find_file(core_csv_dir, "AppendixTable4"), "App_Table_G1", format_app_g1)

        # NOTE: App_Table_A1 mapping removed entirely.

    print(f"\n[OK] All core tables successfully merged and correctly mapped to Paper layout into: {merged_path}")


# -----------------------------
# Main Execution
# -----------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="./anymous", help="Path to anymous data folder")
    ap.add_argument("--core", default="./kg_utility_reasoning.py", help="Path to kg_utility_reasoning.py")
    ap.add_argument("--anchor_script", default="./supplier_anchor_verify_in_one_merge.py",
                    help="Path to supplier_anchor_verify_in_one_merge.py")
    ap.add_argument("--out_dir", default="./result_kg_reproduce", help="Output directory for reproduction run")
    ap.add_argument("--price_xlsx", default="", help="Override price xlsx path")
    ap.add_argument("--media_xlsx", default="", help="Override media xlsx path")
    ap.add_argument("--neo_dir", default="", help="Override neo4j_export dir path")
    ap.add_argument("--min_label_freq", type=int, default=-1, help="Override min label freq")
    args = ap.parse_args()

    ensure_dir(args.out_dir)

    # Locate the actual root folder containing the dataset
    any_root = find_anymous_root(args.input)
    print(f">>> Root data directory determined as: {any_root}")

    price_xlsx = args.price_xlsx.strip() or os.path.join(any_root, "name_price_anonymized.xlsx")
    media_xlsx = args.media_xlsx.strip() or os.path.join(any_root, "media_result.xlsx")
    neo_dir = args.neo_dir.strip() or os.path.join(any_root, "neo4j_export")

    # Validation
    for p in [price_xlsx, media_xlsx]:
        if not os.path.exists(p):
            raise FileNotFoundError(f"Missing required file: {p}")
    if not os.path.isdir(neo_dir):
        raise FileNotFoundError(f"Missing required directory: {neo_dir}")

    # Load metadata, splits, and embeddings
    meta_path = os.path.join(any_root, "anymous_meta.json")
    meta = read_json(meta_path) if os.path.exists(meta_path) else {}
    splits_k_path = os.path.join(any_root, "STEP0_splits_kfold.json")
    splits_g_path = os.path.join(any_root, "STEP0_splits_groupkfold_supplier.json")
    folds_k = read_json(splits_k_path)
    folds_g = read_json(splits_g_path)

    df_emb_map, emb_cols = load_product_embedding_table(any_root)
    fold2emb, cache_n_rows, cache_dim = load_fold_textemb_cache(any_root)

    # Mock py2neo dependency if not present
    try:
        import py2neo  # noqa: F401
    except Exception:
        dummy = types.ModuleType("py2neo")

        class _DummyGraph:
            def __init__(self, *a, **kw):
                raise RuntimeError("Neo4j Graph is disabled in reproduce mode.")

        dummy.Graph = _DummyGraph
        sys.modules["py2neo"] = dummy

    print(">>> Loading core reproduction script...")
    core = load_module("kg_core", args.core)

    try:
        core.EXCEL_PATH = price_xlsx
        core.MEDIA_PATH = media_xlsx
    except Exception:
        pass

    # Apply Monkeypatches to avoid crash in anonymized environments
    core.Neo4jDB = CSVNeo4jDB
    patch_onehotencoder_compat(core)
    patch_fixed_splits(core, folds_k, folds_g)
    patch_step0_fold_text_embedding(core, folds_k, fold2emb)
    patch_product_text_embedding(core, df_emb_map, emb_cols)
    patch_build_X_with_product_textemb(core, df_emb_map, emb_cols)

    n_splits = int(meta.get("n_splits", len(folds_k) or 5))
    random_state = int(meta.get("random_state", getattr(core, "RANDOM_STATE", 7)))
    min_label_freq = int(args.min_label_freq) if int(args.min_label_freq) >= 0 else int(
        getattr(core, "FE_MIN_LABEL_FREQ_FOR_TABLE", 3))

    print("\n=============================================")
    print(" PHASE 1: Running core reasoning logic")
    print("=============================================")
    call_run_all_steps_compat(
        core,
        excel_path=price_xlsx,
        media_path=media_xlsx,
        out_dir=str(args.out_dir),
        neo4j_uri="", neo4j_user="", neo4j_pass="", neo4j_db=str(neo_dir),
        n_splits=n_splits,
        random_state=random_state,
        min_label_freq=min_label_freq,
        heat_ablation=True,
        ppr_heat_teleport_mass=float(meta.get("ppr_heat_teleport_mass", getattr(core, "PPR_HEAT_TELEPORT_MASS", 0.35))),
        metapath_heat_teleport_mass=float(
            meta.get("metapath_heat_teleport_mass", getattr(core, "METAPATH_HEAT_TELEPORT_MASS", 0.35))),
    )

    # Post-run safeguards for outputs required for paper tables
    step0_sum = os.path.join(args.out_dir, "STEP0_paper_5block_paper_summary.csv")
    if not os.path.exists(step0_sum):
        df0 = _load_df0_for_step0(any_root, args.out_dir)
        if hasattr(core, "evaluate_5block_paper"):
            core.evaluate_5block_paper(df0, folds_k, str(args.out_dir), min_label_freq=min_label_freq)

    heat_pairs = os.path.join(args.out_dir, "step3_HEAT_ABLATION__expheat_price_gradient_pairs.csv")
    if not os.path.exists(heat_pairs):
        mech_path = os.path.join(args.out_dir, "STEP3_product_mechanism_proxies.csv")
        if os.path.exists(mech_path) and hasattr(core, "write_heat_ablation_expheat_price_gradient"):
            df0 = _ensure_prod_key(_load_df0_for_step0(any_root, args.out_dir))
            prod_mech = pd.read_csv(mech_path)
            core.write_heat_ablation_expheat_price_gradient(
                df_rows=df0, prod_mech_df=prod_mech, out_dir=str(args.out_dir),
                folds_k=folds_k, folds_g=folds_g, price_col="price",
                supplier_col="supplier", prod_key_col="prod_key",
            )

    # Re-export paper tables specifically
    if hasattr(core, "export_tables_1_to_11_and_appendices_1_to_5"):
        core.export_tables_1_to_11_and_appendices_1_to_5(str(args.out_dir), decimals=3)

    print("\n=============================================")
    print(" PHASE 2: Running supplier anchor verification")
    print("=============================================")
    anchor_mod = load_module("anchor_mod", args.anchor_script)
    anchor_out = os.path.join(args.out_dir, "anchor_merge_outputs")
    ensure_dir(anchor_out)

    # Consistency modification: Dynamically override config paths in the anchor script
    anchor_mod.CONFIG["FILE_FE_SUPPLIER"] = os.path.join(args.out_dir, "STEP1_fe_table_supplier.csv")
    anchor_mod.CONFIG["FILE_PRICE_XLSX"] = price_xlsx
    anchor_mod.CONFIG["FILE_MEDIA_XLSX"] = media_xlsx
    anchor_mod.CONFIG["FILE_NODE_DATAPRODUCT"] = os.path.join(neo_dir, "nodes_dataproduct.csv")
    anchor_mod.CONFIG["FILE_REL_SRC"] = os.path.join(neo_dir, "rel_source_industry.csv")
    anchor_mod.CONFIG["FILE_REL_APP"] = os.path.join(neo_dir, "rel_applied_to.csv")
    anchor_mod.CONFIG["OUTPUT_DIR"] = anchor_out

    anchor_mod.main()

    print("\n=============================================")
    print(" PHASE 3: Merging strictly required outputs")
    print("=============================================")
    merge_excel(args.out_dir)
    print(f"\n[Complete] The full reproduction pipeline finished successfully.")


if __name__ == "__main__":
    main()